 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: instruct_vicuna7b
  model_type: vicuna7b
  use_grad_checkpoint: False
  pretrained: ./output/BLIP2/train_vicua/20250320054/checkpoint_best.pth

datasets:
  changechat_105k:
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        eval:
          name: "blip_caption"

run:
  task: captioning
  batch_size_train: 4
  batch_size_eval: 4
  num_workers: 0

  max_len: 30
  min_len: 
  num_beams: 1
  prompt: 'Please briefly describe the changes in these two images.'

  seed: 42
  output_dir: "output/BLIP2/Caption_coco_opt2.7b"

  evaluate: True
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
